export const SET_POSITION = 'SET_POSITION';
export const SET_WINDOWMESSAGE = 'SET_WINDOWMESSAGE';
export const SET_BIKETYPE = 'SET_BIKETYPE';
export const SET_BEGINPOSITION = 'SET_BEGINPOSITION';
export const SET_FINISHPOSITION = 'SET_FINISHPOSITION';
export const SET_ROUTERNAME = 'SET_ROUTERNAME';
